# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Site settings
title: Baihan's Blog | 林柏翰的博客 
description: Baihan's Blog | 林柏翰的博客
link: http://doerblog.github.io

# Author
author: 
  name: Baihan Lin
  email: DoerLBH@gmail.com
  link: http://doerblog.github.io
  weibo: 
  github: http://github.com/doerlbh


# avatar & Favicon
avatar: http://en.gravatar.com/avatar/c3f17efc644dc613f335001adcd23250?s=1000
favicon: http://en.gravatar.com/avatar/c3f17efc644dc613f335001adcd23250?s=1000

# disqus 设置
disqus:
  shortname: doerlbh

# google analytics 设置
ga:
  id: UA-74038161-4
  url: doerblog.github.io


